packages: []

catalog:
  globals: ^16.2.0

catalogs:
  parsers:
    vue-eslint-parser: ^10.1.3

  plugins:
    "@eslint/js": ^9.27.0
    "@stylistic/eslint-plugin": ^4.4.0
    "@typescript-eslint/eslint-plugin": ^8.32.1
    "@typescript-eslint/parser": ^8.32.1
    "@vitest/eslint-plugin": ^1.2.1
    eslint-config-flat-gitignore: ^2.1.0
    eslint-config-prettier: ^10.1.5
    eslint-plugin-de-morgan: ^1.2.1
    eslint-plugin-import-x: ^4.13.3
    eslint-plugin-n: ^17.18.0
    eslint-plugin-oxlint: ^0.17.0
    eslint-plugin-perfectionist: ^4.13.0
    eslint-plugin-prettier: ^5.4.0
    eslint-plugin-promise: ^7.2.1
    eslint-plugin-unicorn: ^59.0.1
    eslint-plugin-vue: ^10.1.0
    eslint-plugin-vuejs-accessibility: ^2.4.1

  dev:
    "@types/node": ^22.15.27
    eslint: ^9.27.0
    eslint-typegen: ^2.2.0
    nano-staged: ^0.8.0
    oxlint: ^0.17.0
    simple-git-hooks: ^2.13.0
    tsx: ^4.19.4
    typescript: ^5.8.3
    vitest: ^3.1.4
    vue: ^3.5.15
